# Generated by Django 4.1.3 on 2023-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alcohol",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
