# Generated by Django 4.1.3 on 2023-01-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alcohol",
            name="type",
            field=models.CharField(
                choices=[
                    ("Vdk", "Vodka"),
                    ("Ber", "Beer"),
                    ("RdW", "Red Wine"),
                    ("WhW", "White Wine"),
                    ("RsW", "Rose Wine"),
                    ("SpW", "Sparkling Wine"),
                    ("Whs", "Whiskey"),
                    ("Lqr", "Liquor"),
                    ("Brb", "Bourbon"),
                    ("Brd", "Brandy"),
                    ("Mns", "Moonshine"),
                    ("Oth", "Other"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="desc",
            field=models.TextField(default="A default description"),
        ),
    ]
