# Generated by Django 4.1.3 on 2023-01-15 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_alcohol_type_alter_profile_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alcohol",
            name="name",
            field=models.CharField(
                error_messages={
                    "invalid": "Provide a valid name.",
                    "required": "Provide the name of the alcohol.",
                },
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="alcohol",
            name="percentage",
            field=models.FloatField(
                default=30,
                error_messages={
                    "invalid": "Provide a percentage between 0 and 100%!",
                    "required": "Provide the percentage of ethanol in the alcohol.",
                },
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="alcohol",
            name="volume_l",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                error_messages={
                    "invalid": "Provide a valid value!",
                    "required": "Provide the volume of the alcohol in litres.",
                },
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
