# Generated by Django 4.1.3 on 2023-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_alcohol_name_alter_alcohol_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alcohol",
            name="name",
            field=models.CharField(
                error_messages={
                    "invalid": "Provide a valid name.",
                    "required": "Provide the name of the alcohol.",
                    "unique": "Such item already exists!",
                },
                max_length=200,
            ),
        ),
    ]
