# Generated by Django 4.1.3 on 2023-01-15 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_alcohol_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alcohol",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="alcohol",
            name="percentage",
            field=models.FloatField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="alcohol",
            name="volume_l",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
