# Generated by Django 4.1.3 on 2023-01-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_alcohol_name_alter_alcohol_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default_user.png", upload_to="profile_pics"
            ),
        ),
    ]
