# Generated by Django 4.1.3 on 2023-01-18 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
