# Generated by Django 4.1.3 on 2023-01-19 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0012_review_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="alcohol",
            name="reviews",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
