# Generated by Django 4.1.3 on 2023-01-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alcohol_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="alcohol",
            name="alcohol_picture",
            field=models.ImageField(
                default="alcohol_pics/default_alcohol.jpg", upload_to="alcohol_pics"
            ),
        ),
    ]
